### PR TITLE
2.1.0 update

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This is an updated version of #5, which includes updates to the recipe to match the current standards.

Closes #2, closes #5, closes #6, and closes #7.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@conda-forge/myproxyclient, this should be ready for review.

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by cofinoa** [comment]
The update of the conda package to v2.1.0 has been a long outstanding.

Original maintainers appears to be inactive and following conde-forge instructions:
https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

@duncanmmacleod, please would you mind to modify the recipe and add more maintainers at the `recipe/meta.yml` file?
```
extra:
  recipe-maintainers:
    - agoodm
    - jarifibrahim
    - duncanmmacleod
    - philipkershaw
    - cehbrecht
    - cofinoa
```

Of course if @philipkershaw (original developer of the pip package) and @cehbrecht (contributor) agree. 

Then we can mention conda-forge core team, to merge the PR as it's been indicate on point 4 at:
https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

**Comment by cehbrecht** [comment]
@duncanmmacleod @cofinoa I have no rights to edit this PR. There are also conflicts. Do we need to re-render the recipe?

**Comment by cofinoa** [comment]
@cehbrecht we need to solve first who are maintainers of this recipe. 

Then re-render the recipe. IMO, this PR from @duncanmmacleod it's the way to re-render.

I will wait a few days to see if there is any reactions ... and after that, I will open a PR updating the above maintainers and request the action to merge to the conda-forge core team.

**Pull request closed without merging**
